// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/ClickableIcon.tsx";
import * as $$1 from "./islands/CodeBlock.tsx";
import * as $$2 from "./islands/Counter.tsx";
import * as $$3 from "./islands/Examples.tsx";
import * as $$4 from "./islands/IconList.tsx";
import * as $$5 from "./islands/Toast.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/ClickableIcon.tsx": $$0,
    "./islands/CodeBlock.tsx": $$1,
    "./islands/Counter.tsx": $$2,
    "./islands/Examples.tsx": $$3,
    "./islands/IconList.tsx": $$4,
    "./islands/Toast.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
